/*
 * Action type usuarios*
 */
export const FETCH_USUARIOS_LIST = 'FETCH_USUARIOS_LIST';
export const FETCH_USUARIOS_LIST_SUCCESS = 'FETCH_USUARIOS_LIST_SUCCESS';
export const FETCH_USUARIOS_LIST_FAILED = 'FETCH_USUARIOS_LIST_FAILED';

export const FETCH_OBTENER_USUARIO = 'FETCH_OBTENER_USUARIO';
export const FETCH_OBTENER_USUARIO_SUCCESS = 'FETCH_OBTENER_USUARIO_SUCCESS';
export const FETCH_OBTENER_USUARIO_FAILED = 'FETCH_OBTENER_USUARIO_FAILED';